source "https://rubygems.org"

gem "sinatra"
gem "sinatra-contrib"
gem "pg"
gem "erubis"
gem "unicorn"
gem "puma"
gem "httpclient"
gem 'redis'
gem 'hiredis'
gem 'expeditor'
gem 'oj'

gem 'stackprof'
gem 'rack-lineprof'

gem 'dotenv'
